---
title: "Modern Inference"
output: markdowntemplates::minimal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Corso di Laurea Magistrale in Scienze Statistiche ed Economiche, Università degli Studi di Milano-Bicocca, A.A. 2020/21.


## Calendario delle lezioni e materiale didattico

CONFORMAL INFERENCE

* L01 (Giovedì 18 Marzo 10:30-13:30) 3h
   * **Prediction intervals**
   * **Conformal prediction**
   * [Davison A.C. (2003), Statistical Models, Cambridge University Press.  Section 8.3.2]()
   * [Shafer, G. and Vovk, V. (2008). A tutorial on conformal prediction. Journal of Machine Learning
Research, 9:371–421.](https://jmlr.org/papers/volume9/shafer08a/shafer08a.pdf)

* L02 (Lunedì 22 Marzo 12:30-15:30) 3h
   * **Split conformal prediction**
   * **Multi split conformal prediction**
   * [Lei, J., G'Sell, M., Rinaldo, A., Tibshirani, R. J., and Wasserman, L. (2018). Distribution-free
predictive inference for regression. Journal of the American Statistical Association, 113:1094-1111.](https://arxiv.org/pdf/1604.04173.pdf)
   * [Romano, Y., Patterson, E., and Candes, E. J. (2019). Conformalized quantile regression. 33rd Conference on Neural Information Processing Systems](https://arxiv.org/pdf/1905.03222.pdf)
   * [Barber, R. F., Candes, E. J., Ramdas, A., and Tibshirani, R. J. (2021). Predictive inference with
the jackknife+. Annals of Statistics, 49:486–507.](https://arxiv.org/pdf/1905.02928.pdf)

SELECTION, HIGH DIMENSIONAL STATISTICS AND MULTIPLE TESTING

* L03 (Martedì 23 Marzo 9:30-11:30) 2h
   * **The crisis of modern science**
   * **The law of selection**
   * [Ioannidis (2005) Why most published research findings are false
PLoS medicine]()
   * [Goeman (2016) Randomness and the Games of Science. The Challenge of Chance, pp. 91–109, Springer]()
   * [Hung and Fithian (2020) Statistical methods for replicability assessment. The Annals of Applied Statistics. 14: 1063-1087](https://arxiv.org/pdf/1903.08747.pdf)
   
* L04 (Giovedì 25 Marzo 10:30-13:30) 3h
   * **What can go wrong in high dimensions?**
   * **Global tests in high dimensions**
   * [Wainwright (2019) High-Dimensional Statistics: A Non-Asymptotic Viewpoint
Cambridge University Press. Sections 1.1.1, 1.2.1, 1.3.1]()
   * [Donoho D. and Jin J. (2015) Higher Criticism for Large-Scale Inference, Especially for Rare and Weak Effects, Statistical Science, 30:1–25](http://www.stat.cmu.edu/~jiashun/Research/Selected/HC-Review.pdf)
   
* L05 (Lunedì 29 Marzo 12:30-15:30) 3h
   * **Multiple testing: FWER controlling procedures**
   * **Multiple testing: FDR controlling procedures**
   * [Goeman, J.J. and Solari, A. (2014) Multiple Hypothesis Testing in Genomics. Statistics in Medicine, 33, 1946--78]()

VARIABLE SELECTION

* L06 (Martedì 30 Marzo 9:30-11:30) 2h 
   * **Data splitting for high dimensional variable selection**
   * [Dezeure, R., Buhlmann, P., Meier, L., & Meinshausen, N. (2015). High dimensional
inference: Confidence intervals, p-values and r-software
hdi. Statistical Science, 533–558](https://arxiv.org/pdf/1408.4026.pdf)
   
* L07 (Giovedì 8 Aprile 10:30-13:30) 3h 
   * **Stability selection**
   * **Complementary Pairs Stability Selection**
   * [Meinshausen, N. and Buhlmann, P. (2010). Stability selection. JRSS-B, 72:417-473.](https://arxiv.org/pdf/0809.2932.pdf)
   * [Shah, R. D. and Samworth, R. J. (2013). Variable selection with error control: another look at
stability selection. JRSS-B,
75:55-80](http://www.statslab.cam.ac.uk/~rjs57/rssb_1034.pdf)
   
* L08 (Lunedì 12 Aprile 12:30-14:30) 3h 
   * **The knockoff filter: Fixed-X knockoffs**
   * **The knockoff filter: Model-X knockoffs**
   * [Barber, R. F., Candès, E. J., et al. (2015). Controlling the false discovery rate via knockoffs. The Annals of Statistics, 43, 2055–2085](https://arxiv.org/pdf/1404.5609.pdf).
   * [Barber, R. F., Candès, E. J., et al. (2019). A knockoff filter for highdimensional
selective inference. The Annals of Statistics, 47, 2504–
2537](https://arxiv.org/pdf/1602.03574.pdf)

Se non specificato, la lezione è sincrona. 


## Esame
  
L’esame è composto da due parti:

1. Prova scritta (peso 1/3) che si svolgerà in corrispondenza degli appelli d'esame;

2. Analisi dei dati (peso 2/3) da consegnare almeno una settimana prima della prova scritta. 
  
Il voto finale è dato dalla media pesata dei voti delle parti 1. e 2. Lo studente (oppure il docente) può richiedere la prova orale.

### Analisi dei dati

L'analisi dai dati prevede la consegna sulla pagina MOODLE (almeno una settimana prima della prova scritta) di un file TXT per ciascuno dei seguenti 4 data set: 

* Intervalli di previsione: l'obiettivo è costruire intervalli di previsione per il test set di ciascun data set. Gli intervalli verranno valutati in termini di copertura e lunghezza complessiva.

   * Data set [PRED_LOW_train](docs/data/PRED_LOW_train.txt) e [PRED_LOW_test](docs/data/PRED_LOW_test.txt) a bassa dimensionalità
   * Data set [PRED_HIGH_train]() e [PRED_HIGH_test]() ad elevata dimensionalità 
   * Esempio di consegna: [TXT](docs/data/2575_PRED_LOW.txt), [RMD](docs/data/2575_PRED_LOW.Rmd) e [PDF](docs/data/2575_PRED_LOW.pdf). E' obbligatorio rispettare il formato richiesto. 
 
* Selezione delle variabili: l'obiettivo è selezionare l'insieme di variabili "rilevanti" per ciascun data set. La selezione verrà valutata in termini di True Positive Rate e False Discovery Rate. 

   * Data set [VS_LOW](docs/data/VS_LOW.txt) a bassa dimensionalità
   * Data set [VS_HIGH](docs/data/VS_HIGH.txt) ad elevata dimensionalità 
   * Esempio di consegna: [TXT](docs/data/2575_VS_HIGH.txt), [RMD](docs/data/2575_VS_HIGH.Rmd) e [PDF](docs/data/2575_VS_HIGH.pdf). E' obbligatorio rispettare il formato richiesto. 
   
Oltre ai file TXT, bisogna consegnare sulla pagina MOODLE i corrispettivi file PDF contenenti il codice utilizzato (riportare solo il codice strettamente necessario che deve essere riproducibile). 

* L'analisi dei dati può essere consegnata una volta sola;

* Gli studenti che si iscrivono al seguente form entro il 18 Marzo 2021 viene data la possibilità di svolgere l'analisi dei dati in gruppi di (al massimo) tre persone (suddivisi casualemente). Gli studenti che partecipano in gruppo dovranno consegnare almeno una settimana prima del primo appello (entro 20 Aprile 2021 ore 14:30) e preparare una breve presentazione del loro lavoro che si svolgerà in corrispondenza del primo appello (27 Aprile 2021). Tuttavia, non è richiesto di affrontare la prova scritta necessariamente al primo appello;

* Il punteggio ottenuto per l'analisi dei dati sarà valido fino a fine Febbraio 2022. 

### Prova scritta

La prova scritta

* si svolgerà in remoto con il sistema di proctoring;

* sarà in modalità "libro aperto", quindi sarà possibile consultare appunti, libri, codice etc. durante la prova;

* ha come obiettivo la verifica della comprensione degli aspetti matematico-statistici e di programmazione degli argomenti trattati e può prevedere l'utilizzo di un computer su cui è installato il software R o RStudio; 

* consiste in domande sia a risposta multipla o aperta sia a risposta singola in forma numerica. 

### Calendario degli esami

|| Sessione || Data || Luogo  || Orario ||
|-|-|-|-|-|-|-|-|-|-|
||  || ||  ||  || ||
|| Primaverile || 27 Aprile 2021 || Telematica || 14:30 ||
|| Estiva || 22 Giugno 2021 || TBD || TBD ||
|| Estiva || 7 Luglio 2020 || TBD || TBD ||
|| Estiva || Settembre || TBD || TBD ||



